// Code generated by protoc-gen-go. DO NOT EDIT.
// source: translation/v1/translation.proto

package translation

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import v1 "google.golang.org/genproto/googleapis/cloud/speech/v1"
import status "google.golang.org/genproto/googleapis/rpc/status"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MediaTranslationRequest struct {
	// Media Identity
	MediaIdentity string `protobuf:"bytes,1,opt,name=media_identity,json=mediaIdentity,proto3" json:"media_identity,omitempty"`
	// target language
	// ISO-639-1 Code https://cloud.google.com/translate/docs/languages
	LanguageCode string `protobuf:"bytes,2,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	// the format of the transcripts
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// position of the transcript relative to the begginning of the audio or video
	StartTime *duration.Duration `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// names for more possible results
	ExtraNames           string   `protobuf:"bytes,7,opt,name=extra_names,json=extraNames,proto3" json:"extra_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MediaTranslationRequest) Reset()         { *m = MediaTranslationRequest{} }
func (m *MediaTranslationRequest) String() string { return proto.CompactTextString(m) }
func (*MediaTranslationRequest) ProtoMessage()    {}
func (*MediaTranslationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_translation_acf0e9de727f4584, []int{0}
}
func (m *MediaTranslationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaTranslationRequest.Unmarshal(m, b)
}
func (m *MediaTranslationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaTranslationRequest.Marshal(b, m, deterministic)
}
func (dst *MediaTranslationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaTranslationRequest.Merge(dst, src)
}
func (m *MediaTranslationRequest) XXX_Size() int {
	return xxx_messageInfo_MediaTranslationRequest.Size(m)
}
func (m *MediaTranslationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaTranslationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MediaTranslationRequest proto.InternalMessageInfo

func (m *MediaTranslationRequest) GetMediaIdentity() string {
	if m != nil {
		return m.MediaIdentity
	}
	return ""
}

func (m *MediaTranslationRequest) GetLanguageCode() string {
	if m != nil {
		return m.LanguageCode
	}
	return ""
}

func (m *MediaTranslationRequest) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *MediaTranslationRequest) GetStartTime() *duration.Duration {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *MediaTranslationRequest) GetExtraNames() string {
	if m != nil {
		return m.ExtraNames
	}
	return ""
}

type MediaTranslationResponse struct {
	// *Output-only* If set, returns a [google.rpc.Status][google.rpc.Status] message that
	// specifies the error for the operation.
	// return 404 if no result, in this case, client should use StreamingTranslationRequest
	Error *status.Status `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// best translation results
	Results              []*MediaTranslationResponse_TranscriptInfo `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *MediaTranslationResponse) Reset()         { *m = MediaTranslationResponse{} }
func (m *MediaTranslationResponse) String() string { return proto.CompactTextString(m) }
func (*MediaTranslationResponse) ProtoMessage()    {}
func (*MediaTranslationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_translation_acf0e9de727f4584, []int{1}
}
func (m *MediaTranslationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaTranslationResponse.Unmarshal(m, b)
}
func (m *MediaTranslationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaTranslationResponse.Marshal(b, m, deterministic)
}
func (dst *MediaTranslationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaTranslationResponse.Merge(dst, src)
}
func (m *MediaTranslationResponse) XXX_Size() int {
	return xxx_messageInfo_MediaTranslationResponse.Size(m)
}
func (m *MediaTranslationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaTranslationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MediaTranslationResponse proto.InternalMessageInfo

func (m *MediaTranslationResponse) GetError() *status.Status {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *MediaTranslationResponse) GetResults() []*MediaTranslationResponse_TranscriptInfo {
	if m != nil {
		return m.Results
	}
	return nil
}

type MediaTranslationResponse_TranscriptInfo struct {
	// the identity, can be used in TranslationRequest
	TranscriptIdentity string `protobuf:"bytes,1,opt,name=transcript_identity,json=transcriptIdentity,proto3" json:"transcript_identity,omitempty"`
	// ISO-639-1 Code https://cloud.google.com/translate/docs/languages
	LanguageCode         string   `protobuf:"bytes,2,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	Ranking              float32  `protobuf:"fixed32,3,opt,name=ranking,proto3" json:"ranking,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Delay                int64    `protobuf:"varint,5,opt,name=delay,proto3" json:"delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MediaTranslationResponse_TranscriptInfo) Reset() {
	*m = MediaTranslationResponse_TranscriptInfo{}
}
func (m *MediaTranslationResponse_TranscriptInfo) String() string { return proto.CompactTextString(m) }
func (*MediaTranslationResponse_TranscriptInfo) ProtoMessage()    {}
func (*MediaTranslationResponse_TranscriptInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_translation_acf0e9de727f4584, []int{1, 0}
}
func (m *MediaTranslationResponse_TranscriptInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaTranslationResponse_TranscriptInfo.Unmarshal(m, b)
}
func (m *MediaTranslationResponse_TranscriptInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaTranslationResponse_TranscriptInfo.Marshal(b, m, deterministic)
}
func (dst *MediaTranslationResponse_TranscriptInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaTranslationResponse_TranscriptInfo.Merge(dst, src)
}
func (m *MediaTranslationResponse_TranscriptInfo) XXX_Size() int {
	return xxx_messageInfo_MediaTranslationResponse_TranscriptInfo.Size(m)
}
func (m *MediaTranslationResponse_TranscriptInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaTranslationResponse_TranscriptInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MediaTranslationResponse_TranscriptInfo proto.InternalMessageInfo

func (m *MediaTranslationResponse_TranscriptInfo) GetTranscriptIdentity() string {
	if m != nil {
		return m.TranscriptIdentity
	}
	return ""
}

func (m *MediaTranslationResponse_TranscriptInfo) GetLanguageCode() string {
	if m != nil {
		return m.LanguageCode
	}
	return ""
}

func (m *MediaTranslationResponse_TranscriptInfo) GetRanking() float32 {
	if m != nil {
		return m.Ranking
	}
	return 0
}

func (m *MediaTranslationResponse_TranscriptInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *MediaTranslationResponse_TranscriptInfo) GetDelay() int64 {
	if m != nil {
		return m.Delay
	}
	return 0
}

type DetectionRequest struct {
	// the text to be detect
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetectionRequest) Reset()         { *m = DetectionRequest{} }
func (m *DetectionRequest) String() string { return proto.CompactTextString(m) }
func (*DetectionRequest) ProtoMessage()    {}
func (*DetectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_translation_acf0e9de727f4584, []int{2}
}
func (m *DetectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectionRequest.Unmarshal(m, b)
}
func (m *DetectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectionRequest.Marshal(b, m, deterministic)
}
func (dst *DetectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectionRequest.Merge(dst, src)
}
func (m *DetectionRequest) XXX_Size() int {
	return xxx_messageInfo_DetectionRequest.Size(m)
}
func (m *DetectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetectionRequest proto.InternalMessageInfo

func (m *DetectionRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type DetectionResponse struct {
	// *Output-only* the language code of the detection result
	LanguageCode string `protobuf:"bytes,1,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	// *Output-only* The confidence estimate between 0.0 and 1.0. A higher number
	// indicates an estimated greater likelihood that the detection result are
	// correct.
	Confidence           float32  `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetectionResponse) Reset()         { *m = DetectionResponse{} }
func (m *DetectionResponse) String() string { return proto.CompactTextString(m) }
func (*DetectionResponse) ProtoMessage()    {}
func (*DetectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_translation_acf0e9de727f4584, []int{3}
}
func (m *DetectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectionResponse.Unmarshal(m, b)
}
func (m *DetectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectionResponse.Marshal(b, m, deterministic)
}
func (dst *DetectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectionResponse.Merge(dst, src)
}
func (m *DetectionResponse) XXX_Size() int {
	return xxx_messageInfo_DetectionResponse.Size(m)
}
func (m *DetectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetectionResponse proto.InternalMessageInfo

func (m *DetectionResponse) GetLanguageCode() string {
	if m != nil {
		return m.LanguageCode
	}
	return ""
}

func (m *DetectionResponse) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

type TranscriptRequest struct {
	// oneof case 2
	// return translate result by transcript_identity
	TranscriptIdentity string `protobuf:"bytes,4,opt,name=transcript_identity,json=transcriptIdentity,proto3" json:"transcript_identity,omitempty"`
	// position of the transcript relative to the begginning of the audio or video
	StartTime            *duration.Duration `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TranscriptRequest) Reset()         { *m = TranscriptRequest{} }
func (m *TranscriptRequest) String() string { return proto.CompactTextString(m) }
func (*TranscriptRequest) ProtoMessage()    {}
func (*TranscriptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_translation_acf0e9de727f4584, []int{4}
}
func (m *TranscriptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscriptRequest.Unmarshal(m, b)
}
func (m *TranscriptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscriptRequest.Marshal(b, m, deterministic)
}
func (dst *TranscriptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscriptRequest.Merge(dst, src)
}
func (m *TranscriptRequest) XXX_Size() int {
	return xxx_messageInfo_TranscriptRequest.Size(m)
}
func (m *TranscriptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscriptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TranscriptRequest proto.InternalMessageInfo

func (m *TranscriptRequest) GetTranscriptIdentity() string {
	if m != nil {
		return m.TranscriptIdentity
	}
	return ""
}

func (m *TranscriptRequest) GetStartTime() *duration.Duration {
	if m != nil {
		return m.StartTime
	}
	return nil
}

type TranscriptResponse struct {
	Error *status.Status `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// each line of the transcript
	Transcripts []*TranscriptResponse_Cue `protobuf:"bytes,2,rep,name=transcripts,proto3" json:"transcripts,omitempty"`
	// if transcripts ended in this result
	IsEndOfTranscript    bool     `protobuf:"varint,3,opt,name=is_end_of_transcript,json=isEndOfTranscript,proto3" json:"is_end_of_transcript,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranscriptResponse) Reset()         { *m = TranscriptResponse{} }
func (m *TranscriptResponse) String() string { return proto.CompactTextString(m) }
func (*TranscriptResponse) ProtoMessage()    {}
func (*TranscriptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_translation_acf0e9de727f4584, []int{5}
}
func (m *TranscriptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscriptResponse.Unmarshal(m, b)
}
func (m *TranscriptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscriptResponse.Marshal(b, m, deterministic)
}
func (dst *TranscriptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscriptResponse.Merge(dst, src)
}
func (m *TranscriptResponse) XXX_Size() int {
	return xxx_messageInfo_TranscriptResponse.Size(m)
}
func (m *TranscriptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscriptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TranscriptResponse proto.InternalMessageInfo

func (m *TranscriptResponse) GetError() *status.Status {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *TranscriptResponse) GetTranscripts() []*TranscriptResponse_Cue {
	if m != nil {
		return m.Transcripts
	}
	return nil
}

func (m *TranscriptResponse) GetIsEndOfTranscript() bool {
	if m != nil {
		return m.IsEndOfTranscript
	}
	return false
}

type TranscriptResponse_Cue struct {
	// the start and end of the transcripts
	StartTime            *duration.Duration `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *duration.Duration `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Text                 string             `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TranscriptResponse_Cue) Reset()         { *m = TranscriptResponse_Cue{} }
func (m *TranscriptResponse_Cue) String() string { return proto.CompactTextString(m) }
func (*TranscriptResponse_Cue) ProtoMessage()    {}
func (*TranscriptResponse_Cue) Descriptor() ([]byte, []int) {
	return fileDescriptor_translation_acf0e9de727f4584, []int{5, 0}
}
func (m *TranscriptResponse_Cue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscriptResponse_Cue.Unmarshal(m, b)
}
func (m *TranscriptResponse_Cue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscriptResponse_Cue.Marshal(b, m, deterministic)
}
func (dst *TranscriptResponse_Cue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscriptResponse_Cue.Merge(dst, src)
}
func (m *TranscriptResponse_Cue) XXX_Size() int {
	return xxx_messageInfo_TranscriptResponse_Cue.Size(m)
}
func (m *TranscriptResponse_Cue) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscriptResponse_Cue.DiscardUnknown(m)
}

var xxx_messageInfo_TranscriptResponse_Cue proto.InternalMessageInfo

func (m *TranscriptResponse_Cue) GetStartTime() *duration.Duration {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *TranscriptResponse_Cue) GetEndTime() *duration.Duration {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *TranscriptResponse_Cue) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// The top-level message sent by the client for the `StreamingRecognize` method.
// Multiple `StreamingTranslationRequest` messages are sent. The first message
// must contain a `streaming_config` message and must not contain `audio` data.
// All subsequent messages must contain `audio` data and must not contain a
// `streaming_config` message.
type StreamingTranslationRequest struct {
	// The streaming request, which is either a streaming config or audio content.
	//
	// Types that are valid to be assigned to StreamingRequest:
	//	*StreamingTranslationRequest_StreamingConfig
	//	*StreamingTranslationRequest_AudioContent
	StreamingRequest     isStreamingTranslationRequest_StreamingRequest `protobuf_oneof:"streaming_request"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *StreamingTranslationRequest) Reset()         { *m = StreamingTranslationRequest{} }
func (m *StreamingTranslationRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingTranslationRequest) ProtoMessage()    {}
func (*StreamingTranslationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_translation_acf0e9de727f4584, []int{6}
}
func (m *StreamingTranslationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingTranslationRequest.Unmarshal(m, b)
}
func (m *StreamingTranslationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingTranslationRequest.Marshal(b, m, deterministic)
}
func (dst *StreamingTranslationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingTranslationRequest.Merge(dst, src)
}
func (m *StreamingTranslationRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingTranslationRequest.Size(m)
}
func (m *StreamingTranslationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingTranslationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingTranslationRequest proto.InternalMessageInfo

type isStreamingTranslationRequest_StreamingRequest interface {
	isStreamingTranslationRequest_StreamingRequest()
}

type StreamingTranslationRequest_StreamingConfig struct {
	StreamingConfig *v1.RecognitionConfig `protobuf:"bytes,1,opt,name=streaming_config,json=streamingConfig,proto3,oneof"`
}
type StreamingTranslationRequest_AudioContent struct {
	AudioContent []byte `protobuf:"bytes,2,opt,name=audio_content,json=audioContent,proto3,oneof"`
}

func (*StreamingTranslationRequest_StreamingConfig) isStreamingTranslationRequest_StreamingRequest() {}
func (*StreamingTranslationRequest_AudioContent) isStreamingTranslationRequest_StreamingRequest()    {}

func (m *StreamingTranslationRequest) GetStreamingRequest() isStreamingTranslationRequest_StreamingRequest {
	if m != nil {
		return m.StreamingRequest
	}
	return nil
}

func (m *StreamingTranslationRequest) GetStreamingConfig() *v1.RecognitionConfig {
	if x, ok := m.GetStreamingRequest().(*StreamingTranslationRequest_StreamingConfig); ok {
		return x.StreamingConfig
	}
	return nil
}

func (m *StreamingTranslationRequest) GetAudioContent() []byte {
	if x, ok := m.GetStreamingRequest().(*StreamingTranslationRequest_AudioContent); ok {
		return x.AudioContent
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StreamingTranslationRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StreamingTranslationRequest_OneofMarshaler, _StreamingTranslationRequest_OneofUnmarshaler, _StreamingTranslationRequest_OneofSizer, []interface{}{
		(*StreamingTranslationRequest_StreamingConfig)(nil),
		(*StreamingTranslationRequest_AudioContent)(nil),
	}
}

func _StreamingTranslationRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StreamingTranslationRequest)
	// streaming_request
	switch x := m.StreamingRequest.(type) {
	case *StreamingTranslationRequest_StreamingConfig:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StreamingConfig); err != nil {
			return err
		}
	case *StreamingTranslationRequest_AudioContent:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.AudioContent)
	case nil:
	default:
		return fmt.Errorf("StreamingTranslationRequest.StreamingRequest has unexpected type %T", x)
	}
	return nil
}

func _StreamingTranslationRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StreamingTranslationRequest)
	switch tag {
	case 1: // streaming_request.streaming_config
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(v1.RecognitionConfig)
		err := b.DecodeMessage(msg)
		m.StreamingRequest = &StreamingTranslationRequest_StreamingConfig{msg}
		return true, err
	case 2: // streaming_request.audio_content
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.StreamingRequest = &StreamingTranslationRequest_AudioContent{x}
		return true, err
	default:
		return false, nil
	}
}

func _StreamingTranslationRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StreamingTranslationRequest)
	// streaming_request
	switch x := m.StreamingRequest.(type) {
	case *StreamingTranslationRequest_StreamingConfig:
		s := proto.Size(x.StreamingConfig)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamingTranslationRequest_AudioContent:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.AudioContent)))
		n += len(x.AudioContent)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type StreamingTranslationResponse struct {
	// *Output-only* If set, returns a [google.rpc.Status][google.rpc.Status] message that
	// specifies the error for the operation.
	Error *status.Status `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// *Output-only* This repeated list contains zero or more results that
	// correspond to consecutive portions of the audio currently being processed.
	// It contains zero or more `is_final=false` results followed by zero or one
	// `is_final=true` result (the newly settled portion).
	Results              []*StreamingTranslationResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *StreamingTranslationResponse) Reset()         { *m = StreamingTranslationResponse{} }
func (m *StreamingTranslationResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingTranslationResponse) ProtoMessage()    {}
func (*StreamingTranslationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_translation_acf0e9de727f4584, []int{7}
}
func (m *StreamingTranslationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingTranslationResponse.Unmarshal(m, b)
}
func (m *StreamingTranslationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingTranslationResponse.Marshal(b, m, deterministic)
}
func (dst *StreamingTranslationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingTranslationResponse.Merge(dst, src)
}
func (m *StreamingTranslationResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingTranslationResponse.Size(m)
}
func (m *StreamingTranslationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingTranslationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingTranslationResponse proto.InternalMessageInfo

func (m *StreamingTranslationResponse) GetError() *status.Status {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *StreamingTranslationResponse) GetResults() []*StreamingTranslationResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type StreamingTranslationResult struct {
	// *Output-only* Transcript text representing the words that the user spoke.
	Transcript string `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`
	// *Output-only* The confidence estimate between 0.0 and 1.0. A higher number
	// indicates an estimated greater likelihood that the recognized words are
	// correct. This field is typically provided only for the top hypothesis, and
	// only for `is_final=true` results. Clients should not rely on the
	// `confidence` field as it is not guaranteed to be accurate or consistent.
	// The default of 0.0 is a sentinel value indicating `confidence` was not set.
	Confidence float32 `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// *Output-only* An estimate of the likelihood that the recognizer will not
	// change its guess about this interim result. Values range from 0.0
	// (completely unstable) to 1.0 (completely stable).
	// This field is only provided for interim results (`is_final=false`).
	// The default of 0.0 is a sentinel value indicating `stability` was not set.
	Stability float32 `protobuf:"fixed32,3,opt,name=stability,proto3" json:"stability,omitempty"`
	// *Output-only* Time offset relative to the beginning of the audio,
	// and corresponding to the start of the spoken word.
	// This field is only set if `enable_word_time_offsets=true` and only
	// in the top hypothesis.
	// This is an experimental feature and the accuracy of the time offset can
	// vary.
	StartTime *duration.Duration `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// *Output-only* Time offset relative to the beginning of the audio,
	// and corresponding to the end of the spoken word.
	// This field is only set if `enable_word_time_offsets=true` and only
	// in the top hypothesis.
	// This is an experimental feature and the accuracy of the time offset can
	// vary.
	EndTime              *duration.Duration `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StreamingTranslationResult) Reset()         { *m = StreamingTranslationResult{} }
func (m *StreamingTranslationResult) String() string { return proto.CompactTextString(m) }
func (*StreamingTranslationResult) ProtoMessage()    {}
func (*StreamingTranslationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_translation_acf0e9de727f4584, []int{8}
}
func (m *StreamingTranslationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingTranslationResult.Unmarshal(m, b)
}
func (m *StreamingTranslationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingTranslationResult.Marshal(b, m, deterministic)
}
func (dst *StreamingTranslationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingTranslationResult.Merge(dst, src)
}
func (m *StreamingTranslationResult) XXX_Size() int {
	return xxx_messageInfo_StreamingTranslationResult.Size(m)
}
func (m *StreamingTranslationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingTranslationResult.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingTranslationResult proto.InternalMessageInfo

func (m *StreamingTranslationResult) GetTranscript() string {
	if m != nil {
		return m.Transcript
	}
	return ""
}

func (m *StreamingTranslationResult) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

func (m *StreamingTranslationResult) GetStability() float32 {
	if m != nil {
		return m.Stability
	}
	return 0
}

func (m *StreamingTranslationResult) GetStartTime() *duration.Duration {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *StreamingTranslationResult) GetEndTime() *duration.Duration {
	if m != nil {
		return m.EndTime
	}
	return nil
}

// We use Google Translation Service for text translation.
// Translation API Reference: https://cloud.google.com/translate/docs/reference/translate
type TextTranslationRequest struct {
	// The text to translate
	Text []string `protobuf:"bytes,1,rep,name=text,proto3" json:"text,omitempty"`
	// The language to use for translation of the text
	// ISO-639-1 Code https://cloud.google.com/translate/docs/languages
	TargetLanguageCode string `protobuf:"bytes,2,opt,name=target_language_code,json=targetLanguageCode,proto3" json:"target_language_code,omitempty"`
	// The language of the source text
	SourceLanguageCode   string   `protobuf:"bytes,3,opt,name=source_language_code,json=sourceLanguageCode,proto3" json:"source_language_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextTranslationRequest) Reset()         { *m = TextTranslationRequest{} }
func (m *TextTranslationRequest) String() string { return proto.CompactTextString(m) }
func (*TextTranslationRequest) ProtoMessage()    {}
func (*TextTranslationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_translation_acf0e9de727f4584, []int{9}
}
func (m *TextTranslationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextTranslationRequest.Unmarshal(m, b)
}
func (m *TextTranslationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextTranslationRequest.Marshal(b, m, deterministic)
}
func (dst *TextTranslationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextTranslationRequest.Merge(dst, src)
}
func (m *TextTranslationRequest) XXX_Size() int {
	return xxx_messageInfo_TextTranslationRequest.Size(m)
}
func (m *TextTranslationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TextTranslationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TextTranslationRequest proto.InternalMessageInfo

func (m *TextTranslationRequest) GetText() []string {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *TextTranslationRequest) GetTargetLanguageCode() string {
	if m != nil {
		return m.TargetLanguageCode
	}
	return ""
}

func (m *TextTranslationRequest) GetSourceLanguageCode() string {
	if m != nil {
		return m.SourceLanguageCode
	}
	return ""
}

type TextTranslationResponse struct {
	Error *status.Status `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// translation results for the requested text
	Results              []*TextTranslationResponse_Text `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *TextTranslationResponse) Reset()         { *m = TextTranslationResponse{} }
func (m *TextTranslationResponse) String() string { return proto.CompactTextString(m) }
func (*TextTranslationResponse) ProtoMessage()    {}
func (*TextTranslationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_translation_acf0e9de727f4584, []int{10}
}
func (m *TextTranslationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextTranslationResponse.Unmarshal(m, b)
}
func (m *TextTranslationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextTranslationResponse.Marshal(b, m, deterministic)
}
func (dst *TextTranslationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextTranslationResponse.Merge(dst, src)
}
func (m *TextTranslationResponse) XXX_Size() int {
	return xxx_messageInfo_TextTranslationResponse.Size(m)
}
func (m *TextTranslationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TextTranslationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TextTranslationResponse proto.InternalMessageInfo

func (m *TextTranslationResponse) GetError() *status.Status {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *TextTranslationResponse) GetResults() []*TextTranslationResponse_Text {
	if m != nil {
		return m.Results
	}
	return nil
}

type TextTranslationResponse_Text struct {
	// The source language of the text detected
	SourceLanguage string `protobuf:"bytes,1,opt,name=source_language,json=sourceLanguage,proto3" json:"source_language,omitempty"`
	// The translated Text
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextTranslationResponse_Text) Reset()         { *m = TextTranslationResponse_Text{} }
func (m *TextTranslationResponse_Text) String() string { return proto.CompactTextString(m) }
func (*TextTranslationResponse_Text) ProtoMessage()    {}
func (*TextTranslationResponse_Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_translation_acf0e9de727f4584, []int{10, 0}
}
func (m *TextTranslationResponse_Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextTranslationResponse_Text.Unmarshal(m, b)
}
func (m *TextTranslationResponse_Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextTranslationResponse_Text.Marshal(b, m, deterministic)
}
func (dst *TextTranslationResponse_Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextTranslationResponse_Text.Merge(dst, src)
}
func (m *TextTranslationResponse_Text) XXX_Size() int {
	return xxx_messageInfo_TextTranslationResponse_Text.Size(m)
}
func (m *TextTranslationResponse_Text) XXX_DiscardUnknown() {
	xxx_messageInfo_TextTranslationResponse_Text.DiscardUnknown(m)
}

var xxx_messageInfo_TextTranslationResponse_Text proto.InternalMessageInfo

func (m *TextTranslationResponse_Text) GetSourceLanguage() string {
	if m != nil {
		return m.SourceLanguage
	}
	return ""
}

func (m *TextTranslationResponse_Text) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*MediaTranslationRequest)(nil), "sagittarius.translation.v1.MediaTranslationRequest")
	proto.RegisterType((*MediaTranslationResponse)(nil), "sagittarius.translation.v1.MediaTranslationResponse")
	proto.RegisterType((*MediaTranslationResponse_TranscriptInfo)(nil), "sagittarius.translation.v1.MediaTranslationResponse.TranscriptInfo")
	proto.RegisterType((*DetectionRequest)(nil), "sagittarius.translation.v1.DetectionRequest")
	proto.RegisterType((*DetectionResponse)(nil), "sagittarius.translation.v1.DetectionResponse")
	proto.RegisterType((*TranscriptRequest)(nil), "sagittarius.translation.v1.TranscriptRequest")
	proto.RegisterType((*TranscriptResponse)(nil), "sagittarius.translation.v1.TranscriptResponse")
	proto.RegisterType((*TranscriptResponse_Cue)(nil), "sagittarius.translation.v1.TranscriptResponse.Cue")
	proto.RegisterType((*StreamingTranslationRequest)(nil), "sagittarius.translation.v1.StreamingTranslationRequest")
	proto.RegisterType((*StreamingTranslationResponse)(nil), "sagittarius.translation.v1.StreamingTranslationResponse")
	proto.RegisterType((*StreamingTranslationResult)(nil), "sagittarius.translation.v1.StreamingTranslationResult")
	proto.RegisterType((*TextTranslationRequest)(nil), "sagittarius.translation.v1.TextTranslationRequest")
	proto.RegisterType((*TextTranslationResponse)(nil), "sagittarius.translation.v1.TextTranslationResponse")
	proto.RegisterType((*TextTranslationResponse_Text)(nil), "sagittarius.translation.v1.TextTranslationResponse.Text")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TranslationClient is the client API for Translation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TranslationClient interface {
	// Translate media(audio or video) by media identity
	TranslateMedia(ctx context.Context, in *MediaTranslationRequest, opts ...grpc.CallOption) (*MediaTranslationResponse, error)
	// detect the language of text
	DetectLanguage(ctx context.Context, in *DetectionRequest, opts ...grpc.CallOption) (*DetectionResponse, error)
	Transcript(ctx context.Context, in *TranscriptRequest, opts ...grpc.CallOption) (*TranscriptResponse, error)
	// Performs bidirectional streaming audio translation: receive results while
	// sending audio. This method is only available via the gRPC API (not REST).
	StreamingTranslation(ctx context.Context, opts ...grpc.CallOption) (Translation_StreamingTranslationClient, error)
	// Translate text by Google Translation Service
	TranslateText(ctx context.Context, in *TextTranslationRequest, opts ...grpc.CallOption) (*TextTranslationResponse, error)
}

type translationClient struct {
	cc *grpc.ClientConn
}

func NewTranslationClient(cc *grpc.ClientConn) TranslationClient {
	return &translationClient{cc}
}

func (c *translationClient) TranslateMedia(ctx context.Context, in *MediaTranslationRequest, opts ...grpc.CallOption) (*MediaTranslationResponse, error) {
	out := new(MediaTranslationResponse)
	err := c.cc.Invoke(ctx, "/sagittarius.translation.v1.Translation/TranslateMedia", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationClient) DetectLanguage(ctx context.Context, in *DetectionRequest, opts ...grpc.CallOption) (*DetectionResponse, error) {
	out := new(DetectionResponse)
	err := c.cc.Invoke(ctx, "/sagittarius.translation.v1.Translation/DetectLanguage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationClient) Transcript(ctx context.Context, in *TranscriptRequest, opts ...grpc.CallOption) (*TranscriptResponse, error) {
	out := new(TranscriptResponse)
	err := c.cc.Invoke(ctx, "/sagittarius.translation.v1.Translation/Transcript", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationClient) StreamingTranslation(ctx context.Context, opts ...grpc.CallOption) (Translation_StreamingTranslationClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Translation_serviceDesc.Streams[0], "/sagittarius.translation.v1.Translation/StreamingTranslation", opts...)
	if err != nil {
		return nil, err
	}
	x := &translationStreamingTranslationClient{stream}
	return x, nil
}

type Translation_StreamingTranslationClient interface {
	Send(*StreamingTranslationRequest) error
	Recv() (*StreamingTranslationResponse, error)
	grpc.ClientStream
}

type translationStreamingTranslationClient struct {
	grpc.ClientStream
}

func (x *translationStreamingTranslationClient) Send(m *StreamingTranslationRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *translationStreamingTranslationClient) Recv() (*StreamingTranslationResponse, error) {
	m := new(StreamingTranslationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *translationClient) TranslateText(ctx context.Context, in *TextTranslationRequest, opts ...grpc.CallOption) (*TextTranslationResponse, error) {
	out := new(TextTranslationResponse)
	err := c.cc.Invoke(ctx, "/sagittarius.translation.v1.Translation/TranslateText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranslationServer is the server API for Translation service.
type TranslationServer interface {
	// Translate media(audio or video) by media identity
	TranslateMedia(context.Context, *MediaTranslationRequest) (*MediaTranslationResponse, error)
	// detect the language of text
	DetectLanguage(context.Context, *DetectionRequest) (*DetectionResponse, error)
	Transcript(context.Context, *TranscriptRequest) (*TranscriptResponse, error)
	// Performs bidirectional streaming audio translation: receive results while
	// sending audio. This method is only available via the gRPC API (not REST).
	StreamingTranslation(Translation_StreamingTranslationServer) error
	// Translate text by Google Translation Service
	TranslateText(context.Context, *TextTranslationRequest) (*TextTranslationResponse, error)
}

func RegisterTranslationServer(s *grpc.Server, srv TranslationServer) {
	s.RegisterService(&_Translation_serviceDesc, srv)
}

func _Translation_TranslateMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MediaTranslationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServer).TranslateMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sagittarius.translation.v1.Translation/TranslateMedia",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServer).TranslateMedia(ctx, req.(*MediaTranslationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translation_DetectLanguage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServer).DetectLanguage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sagittarius.translation.v1.Translation/DetectLanguage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServer).DetectLanguage(ctx, req.(*DetectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translation_Transcript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServer).Transcript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sagittarius.translation.v1.Translation/Transcript",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServer).Transcript(ctx, req.(*TranscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translation_StreamingTranslation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranslationServer).StreamingTranslation(&translationStreamingTranslationServer{stream})
}

type Translation_StreamingTranslationServer interface {
	Send(*StreamingTranslationResponse) error
	Recv() (*StreamingTranslationRequest, error)
	grpc.ServerStream
}

type translationStreamingTranslationServer struct {
	grpc.ServerStream
}

func (x *translationStreamingTranslationServer) Send(m *StreamingTranslationResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *translationStreamingTranslationServer) Recv() (*StreamingTranslationRequest, error) {
	m := new(StreamingTranslationRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Translation_TranslateText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextTranslationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServer).TranslateText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sagittarius.translation.v1.Translation/TranslateText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServer).TranslateText(ctx, req.(*TextTranslationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Translation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sagittarius.translation.v1.Translation",
	HandlerType: (*TranslationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TranslateMedia",
			Handler:    _Translation_TranslateMedia_Handler,
		},
		{
			MethodName: "DetectLanguage",
			Handler:    _Translation_DetectLanguage_Handler,
		},
		{
			MethodName: "Transcript",
			Handler:    _Translation_Transcript_Handler,
		},
		{
			MethodName: "TranslateText",
			Handler:    _Translation_TranslateText_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingTranslation",
			Handler:       _Translation_StreamingTranslation_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "translation/v1/translation.proto",
}

func init() {
	proto.RegisterFile("translation/v1/translation.proto", fileDescriptor_translation_acf0e9de727f4584)
}

var fileDescriptor_translation_acf0e9de727f4584 = []byte{
	// 1060 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x41, 0x6f, 0xe3, 0x44,
	0x14, 0xde, 0x49, 0xd2, 0x76, 0xfb, 0xd2, 0x76, 0xdb, 0x69, 0xb4, 0x35, 0xd9, 0xb2, 0x04, 0xa3,
	0x65, 0xb3, 0x2b, 0x6a, 0xb7, 0x69, 0x05, 0xa5, 0x17, 0xa4, 0x66, 0x11, 0xbb, 0xd2, 0x02, 0x95,
	0xb7, 0x42, 0x08, 0x09, 0x59, 0x53, 0x7b, 0x62, 0x2c, 0x12, 0x3b, 0x8c, 0xc7, 0x55, 0x57, 0x55,
	0x39, 0x70, 0xe3, 0x80, 0xb4, 0x12, 0xb7, 0xfd, 0x09, 0xdc, 0x38, 0xf2, 0x2b, 0x00, 0x71, 0x41,
	0x82, 0x23, 0x27, 0x7e, 0x01, 0x47, 0xe4, 0x37, 0x76, 0xec, 0xa6, 0x49, 0xb6, 0xc9, 0x2d, 0xf3,
	0xde, 0xbc, 0x79, 0xdf, 0x7b, 0xf3, 0xcd, 0xf7, 0x1c, 0x68, 0x48, 0xc1, 0x82, 0xa8, 0xcb, 0xa4,
	0x1f, 0x06, 0xe6, 0xe9, 0x8e, 0x59, 0x58, 0x1a, 0x7d, 0x11, 0xca, 0x90, 0xd6, 0x23, 0xe6, 0xf9,
	0x52, 0x32, 0xe1, 0xc7, 0x91, 0x51, 0x74, 0x9f, 0xee, 0xd4, 0x37, 0xbd, 0x30, 0xf4, 0xba, 0xdc,
	0x64, 0x7d, 0xdf, 0x64, 0x41, 0x10, 0x4a, 0xf4, 0x44, 0x2a, 0xb2, 0x7e, 0x37, 0xf5, 0xe2, 0xea,
	0x24, 0xee, 0x98, 0x6e, 0x2c, 0x0a, 0x27, 0xd7, 0x37, 0x52, 0xbf, 0xe8, 0x3b, 0x66, 0x24, 0x99,
	0x8c, 0xb3, 0xc0, 0x07, 0xa9, 0xc3, 0xe9, 0x86, 0xb1, 0x6b, 0x46, 0x7d, 0xce, 0x9d, 0xaf, 0x12,
	0x70, 0xb8, 0xb6, 0xd5, 0x5a, 0x6d, 0xd5, 0xff, 0x24, 0xb0, 0xf1, 0x31, 0x77, 0x7d, 0x76, 0x9c,
	0x23, 0xb3, 0xf8, 0x37, 0x31, 0x8f, 0x24, 0xbd, 0x07, 0x2b, 0xbd, 0xc4, 0x65, 0xfb, 0x2e, 0x0f,
	0xa4, 0x2f, 0x9f, 0x6b, 0xa4, 0x41, 0x9a, 0x8b, 0xd6, 0x32, 0x5a, 0x9f, 0xa4, 0x46, 0xfa, 0x16,
	0x2c, 0x77, 0x59, 0xe0, 0xc5, 0xcc, 0xe3, 0xb6, 0x13, 0xba, 0x5c, 0x2b, 0xe1, 0xae, 0xa5, 0xcc,
	0xd8, 0x0e, 0x5d, 0x4e, 0x6f, 0xc3, 0x7c, 0x27, 0x14, 0x3d, 0x26, 0xb5, 0x32, 0x7a, 0xd3, 0x15,
	0xdd, 0x07, 0x88, 0x24, 0x13, 0xd2, 0x96, 0x7e, 0x8f, 0x6b, 0xf3, 0x0d, 0xd2, 0xac, 0xb6, 0x5e,
	0x33, 0x14, 0x7e, 0x23, 0x2b, 0xdc, 0x78, 0x94, 0x16, 0x6e, 0x2d, 0xe2, 0xe6, 0x63, 0xbf, 0xc7,
	0xe9, 0x1b, 0x50, 0xe5, 0x67, 0x52, 0x30, 0x3b, 0x60, 0x3d, 0x1e, 0x69, 0x0b, 0x78, 0x2c, 0xa0,
	0xe9, 0x93, 0xc4, 0xa2, 0xff, 0x56, 0x02, 0xed, 0x6a, 0x69, 0x51, 0x3f, 0x0c, 0x22, 0x4e, 0x9b,
	0x30, 0xc7, 0x85, 0x08, 0x05, 0x96, 0x54, 0x6d, 0xd1, 0x2c, 0xa5, 0xe8, 0x3b, 0xc6, 0x33, 0xec,
	0xa5, 0xa5, 0x36, 0xd0, 0x2f, 0x61, 0x41, 0xf0, 0x28, 0xee, 0xca, 0x48, 0x2b, 0x35, 0xca, 0xcd,
	0x6a, 0xab, 0x6d, 0x8c, 0xbf, 0x51, 0x63, 0x5c, 0x42, 0x03, 0x6d, 0x8e, 0xf0, 0xfb, 0xf2, 0x49,
	0xd0, 0x09, 0xad, 0xec, 0xcc, 0xfa, 0x4f, 0x04, 0x56, 0x2e, 0xfb, 0xa8, 0x09, 0xeb, 0x72, 0x60,
	0x19, 0x6e, 0x3e, 0xcd, 0x5d, 0xd3, 0xdd, 0x80, 0x06, 0x0b, 0x82, 0x05, 0x5f, 0xfb, 0x81, 0x87,
	0x57, 0x50, 0xb2, 0xb2, 0x25, 0xa5, 0x50, 0x91, 0xcc, 0x8b, 0xb4, 0x4a, 0xa3, 0xdc, 0x5c, 0xb4,
	0xf0, 0x37, 0xad, 0xc1, 0x9c, 0xcb, 0xbb, 0xec, 0xb9, 0x36, 0xd7, 0x20, 0xcd, 0xb2, 0xa5, 0x16,
	0xfa, 0xdb, 0xb0, 0xfa, 0x88, 0x4b, 0xee, 0x14, 0x59, 0x92, 0x44, 0xf3, 0x33, 0x99, 0xc2, 0xc3,
	0xdf, 0xfa, 0xe7, 0xb0, 0x56, 0xd8, 0x97, 0xb6, 0xfc, 0x0a, 0x4a, 0x32, 0x02, 0xe5, 0x5d, 0x00,
	0x27, 0x0c, 0x3a, 0x49, 0xd1, 0x8e, 0xaa, 0xa3, 0x64, 0x15, 0x2c, 0xfa, 0xb7, 0xb0, 0x96, 0x77,
	0x2b, 0x83, 0x30, 0xa6, 0x61, 0x95, 0xb1, 0x0d, 0x9b, 0x99, 0x75, 0xfa, 0xef, 0x25, 0xa0, 0x45,
	0x00, 0x53, 0xd3, 0xe9, 0x18, 0xaa, 0x39, 0xa0, 0x8c, 0x52, 0xad, 0x49, 0x94, 0xba, 0x9a, 0xce,
	0x68, 0xc7, 0xdc, 0x2a, 0x1e, 0x43, 0x4d, 0xa8, 0xf9, 0x91, 0xcd, 0x03, 0xd7, 0x0e, 0x3b, 0x76,
	0xee, 0xc0, 0x9b, 0xbe, 0x69, 0xad, 0xf9, 0xd1, 0x87, 0x81, 0xfb, 0x69, 0x27, 0x3f, 0xa9, 0xfe,
	0x3d, 0x81, 0x72, 0x3b, 0xe6, 0x43, 0x9d, 0x20, 0x53, 0xbc, 0xbf, 0x3d, 0xb8, 0x99, 0xe4, 0xc3,
	0xb8, 0xd2, 0xab, 0xe2, 0x16, 0x78, 0xe0, 0x62, 0x54, 0xc6, 0x96, 0x72, 0x81, 0x2d, 0x3f, 0x13,
	0xb8, 0xf3, 0x4c, 0x0a, 0xce, 0x7a, 0x7e, 0xe0, 0x8d, 0xd0, 0xa1, 0xcf, 0x60, 0x35, 0xca, 0xdc,
	0x36, 0x72, 0xc1, 0x4b, 0x91, 0x3e, 0xc8, 0x32, 0xa2, 0xb2, 0x19, 0xa9, 0xb2, 0x9d, 0xee, 0x18,
	0x16, 0x77, 0x42, 0x2f, 0xf0, 0x93, 0x53, 0xda, 0x18, 0xf0, 0xf8, 0x86, 0x75, 0x6b, 0x70, 0x88,
	0x32, 0xd1, 0x7b, 0xb0, 0xcc, 0x62, 0xd7, 0x0f, 0x93, 0x33, 0x25, 0x0f, 0x24, 0x96, 0xb1, 0xf4,
	0xf8, 0x86, 0xb5, 0x84, 0xe6, 0xb6, 0xb2, 0x1e, 0xae, 0xc3, 0x5a, 0x9e, 0x5e, 0x28, 0x4c, 0xfa,
	0x4b, 0x02, 0x9b, 0xa3, 0x31, 0x4f, 0xcd, 0x88, 0xa3, 0x61, 0x81, 0x79, 0x77, 0x12, 0x1b, 0xc6,
	0x24, 0x8d, 0xbb, 0x72, 0xa0, 0x29, 0xfa, 0xbf, 0x04, 0xea, 0xe3, 0xf7, 0x25, 0x6f, 0xac, 0x40,
	0x11, 0xf5, 0x0a, 0x0b, 0x96, 0x57, 0xbd, 0x41, 0xba, 0x09, 0x09, 0x0d, 0x4e, 0xfc, 0x6e, 0xf2,
	0xc8, 0x94, 0x96, 0xe4, 0x86, 0x21, 0x46, 0x55, 0x66, 0x64, 0xd4, 0xdc, 0x75, 0x19, 0xa5, 0xbf,
	0x20, 0x70, 0xfb, 0x98, 0x9f, 0xc9, 0x11, 0xc4, 0xc9, 0xa5, 0xa9, 0x9c, 0x91, 0x8d, 0x6e, 0x43,
	0x4d, 0x32, 0xe1, 0x71, 0x69, 0x8f, 0x92, 0x4c, 0xaa, 0x7c, 0x4f, 0x8b, 0x92, 0xb4, 0x0d, 0xb5,
	0x28, 0x8c, 0x85, 0xc3, 0x87, 0x22, 0x14, 0x85, 0xa9, 0xf2, 0x15, 0x23, 0xf4, 0xbf, 0x09, 0x6c,
	0x5c, 0x81, 0x34, 0x35, 0x2f, 0xac, 0x61, 0x5e, 0xec, 0x4f, 0x54, 0x89, 0xd1, 0xf9, 0xd0, 0x9e,
	0x4f, 0x9b, 0x36, 0x54, 0x12, 0x03, 0xbd, 0x0f, 0xb7, 0x86, 0x6a, 0x4a, 0x79, 0xb0, 0x72, 0xb9,
	0x9c, 0x41, 0x0b, 0x4b, 0xf9, 0x7b, 0x6d, 0xfd, 0x35, 0x0f, 0xd5, 0x42, 0x2a, 0xfa, 0x6b, 0x36,
	0xc2, 0xba, 0x4c, 0x72, 0x1c, 0x80, 0x74, 0x77, 0xba, 0x19, 0x89, 0xd7, 0x55, 0xdf, 0x9b, 0x65,
	0xb0, 0xea, 0xd6, 0x77, 0x7f, 0xfc, 0xf3, 0x63, 0xe9, 0xa9, 0xfe, 0x51, 0xf2, 0x85, 0x83, 0x5f,
	0x26, 0xe6, 0xf9, 0xe5, 0xcf, 0x96, 0x0b, 0x33, 0x2b, 0xd2, 0x3c, 0xbf, 0x74, 0x85, 0x17, 0x66,
	0xce, 0xfa, 0x83, 0x73, 0xf5, 0x45, 0x72, 0x71, 0x40, 0x1e, 0xd2, 0x17, 0x04, 0x56, 0xd4, 0x00,
	0x1b, 0x34, 0xe2, 0x9d, 0x49, 0xe0, 0x86, 0x87, 0x62, 0x7d, 0xeb, 0x9a, 0xbb, 0xd3, 0x1a, 0xde,
	0xc4, 0x1a, 0xee, 0xe8, 0xeb, 0x49, 0x0d, 0x03, 0xb0, 0x2e, 0xee, 0x3b, 0x50, 0xbc, 0x7d, 0x49,
	0x00, 0x72, 0xfd, 0xa6, 0x5b, 0xd7, 0x9d, 0x18, 0x0a, 0x8f, 0x31, 0xdd, 0x80, 0xd1, 0xb7, 0x10,
	0xd0, 0x7d, 0x5d, 0x1f, 0x7c, 0xd3, 0xa2, 0xdf, 0x1c, 0x31, 0x66, 0x93, 0x7e, 0xfd, 0x40, 0xa0,
	0x36, 0x4a, 0x70, 0xe8, 0x7b, 0xd3, 0x4b, 0x99, 0x02, 0xbc, 0x3f, 0x83, 0x06, 0x22, 0xf4, 0x26,
	0xd9, 0x26, 0xf4, 0x17, 0x02, 0xcb, 0x03, 0x46, 0x22, 0xe1, 0x5b, 0x53, 0xbd, 0x1d, 0x85, 0x61,
	0x77, 0x86, 0xf7, 0xa6, 0x7f, 0x80, 0x9d, 0x7b, 0x5f, 0xdf, 0xc3, 0xce, 0xf1, 0x33, 0x59, 0x20,
	0xdf, 0x28, 0xe1, 0xb9, 0x28, 0xfe, 0x65, 0x38, 0x20, 0x0f, 0x0f, 0xdb, 0xf0, 0x3a, 0xf3, 0x27,
	0x64, 0x3e, 0x5c, 0x2d, 0xa4, 0x3d, 0x4a, 0x74, 0xf1, 0x88, 0x7c, 0x51, 0x2d, 0xec, 0xf9, 0x8f,
	0x90, 0x93, 0x79, 0x14, 0xcc, 0xdd, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x44, 0xae, 0x9f,
	0x9f, 0x0c, 0x00, 0x00,
}
